<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
//the left value is the key stored in the db and the right value is ie display value
//to translate, only modify the right value in each key/value pair
$app_list_strings = array (
//e.g. auf Deutsch 'Contacts'=>'Contakten',
  'language_pack_name' => 'US English',
  'moduleList' =>
  array (
    'Home' => 'Home',
    'Contacts' => 'Contacts',
    'Accounts' => 'Accounts',
    'Opportunities' => 'Opportunities',
    'Cases' => 'Cases',
    'Notes' => 'Notes',
    'Calls' => 'Calls',
    'Emails' => 'Emails',
    'Meetings' => 'Meetings',
    'Tasks' => 'Tasks',
    'Calendar' => 'Calendar',
    'Leads' => 'Leads',
    'Currencies' => 'Currencies',
    'Project' => 'Project',
    'Contracts'=>'Contracts',
    'Quotes' => 'Quotes',
    'Products' => 'Quoted Line Items',
    'WebLogicHooks' => 'Web Logic Hooks',
    'ProductCategories' => 'Product Categories',
    'ProductTypes' => 'Product Types',
    'ProductTemplates' => 'Product Catalog',
    'Reports' => 'Reports',
    'Forecasts' => 'Forecasts',
    'ForecastWorksheets' => 'Forecast Worksheets',
    'ForecastManagerWorksheets' => 'Forecast Manager Worksheets',
    'MergeRecords'=>'Merge Records',
    'Quotas' => 'Quotas',
    'Teams' => 'Teams',
    'TeamNotices' => 'Team Notices',
    'Manufacturers' => 'Manufacturers',
    'Activities' => 'Activities',
    'Comments' => 'Comments',
    'Subscriptions' => 'Subscriptions',
    'Bugs' => 'Bugs',
    'Feeds' => 'RSS',
    'iFrames'=>'My Sites',
    'TimePeriods'=>'Time Periods',
    'TaxRates'=>'Tax Rates',
    'ContractTypes' => 'Contract Types',
    'Schedulers'=>'Schedulers',
    'Project'=>'Projects',
    'ProjectTask'=>'Project Tasks',
    'Campaigns'=>'Campaigns',
    'CampaignLog'=>'Campaign Log',
    'CampaignTrackers'=>'Campaign Trackers',
    'Documents'=>'Documents',
    'DocumentRevisions'=>'Document Revisions',
    'Connectors'=>'Connectors',
    'Roles'=>'Roles',
    'Notifications'=>'Notifications',
    'Sync'=>'Sync',
//BEGIN SUGARCRM flav=ent ONLY
    'ReportMaker' => 'Advanced Reports',
    'DataSets' => 'Data Formats',
    'CustomQueries' => 'Custom Queries',
    'pmse_Inbox' => 'Processes',
    'pmse_Project' => 'Process Definitions',
    'pmse_Business_Rules' => 'Process Business Rules',
    'pmse_Emails_Templates' => 'Process Email Templates',
//END SUGARCRM flav=ent ONLY
    'WorkFlow' => 'Workflow Definitions',
    'EAPM' => 'External Accounts',
    'Worksheet' => 'Worksheet',
    'Users' => 'Users',
    'Employees' => 'Employees',
    'Administration' => 'Administration',
    'ACLRoles' => 'Roles',
    'InboundEmail' => 'Inbound Email',
    'Releases' => 'Releases',
    'Prospects' => 'Targets',
    'Queues' => 'Queues',
    'EmailMarketing' => 'Email Marketing',
    'EmailTemplates' => 'Email Templates',
    'SNIP' => "Email Archiving",
    'ProspectLists' => 'Target Lists',
    'SavedSearch' => 'Saved Searches',
    'UpgradeWizard' => 'Upgrade Wizard',
    'Trackers' => 'Trackers',
    'TrackerPerfs' => 'Tracker Performance',
    'TrackerSessions' => 'Tracker Sessions',
    'TrackerQueries' => 'Tracker Queries',
    'FAQ' => 'FAQ',
    'Newsletters' => 'Newsletters',
  	'SugarFavorites'=>'Favorites',
	'PdfManager' => 'PDF Manager',

    'OAuthKeys' => 'OAuth Consumer Keys',
    'OAuthTokens' => 'OAuth Tokens',
    'Filters' => 'Filters',
    'UserSignatures' => 'User Signatures',
    'Shippers' => 'Shipping Providers',
    'Styleguide' => 'Styleguide',
    'Feedbacks' => 'Feedbacks',
    'Tags' => 'Tags',
    'Categories' => 'Categories',
  );

